name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GH_REPO: ${{ github.repository }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
      contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Compile LaTeX
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: latino.tex
          # The working directory for the latex compiler to be invoked
          # working_directory: # optional
          # LaTeX engine to be used
          compiler: pdflatex
          # Extra arguments to be passed to the latex compiler
          # args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          # Install extra packages by apt-get
          # extra_system_packages: # optional
      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: vademecum.pdf
          path: ./latino.pdf
      - name: Publish Release
        run: gh release create stable --target $GITHUB_SHA ./latino.pdf ./vademecum.pdf
